version: '3.1'

services:

  wordpress1:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: exampleuser1
      WORDPRESS_DB_PASSWORD: examplepass1
      WORDPRESS_DB_NAME: exampledb1
    volumes:
      - wordpress:/var/www/html

  db1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb1
      MYSQL_USER: exampleuser1
      MYSQL_PASSWORD: examplepass1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress1:
  db1:
