version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8885:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  adguard-home:
        container_name: adguard-home
        image: adguard/adguardhome
        restart: always

        cap_add:
            - NET_ADMIN

        ports:
            - 53/tcp
            - 53:53/udp
            - 67/udp
            - 68/tcp
            - 68/udp
            - 81:80/tcp
            - 443/tcp
            - 853/tcp
            - 3000:3000/tcp

        hostname: adguard-home-dns
        dns:
            - 127.0.0.1
            - 1.1.1.1
volumes:
  wordpress:
  db:
