version: '3.1'

services:

  wordpress1:
    image: wordpress
    restart: always
    ports:
      - 8886:80
    environment:
      WORDPRESS_DB_HOST: db1
      WORDPRESS_DB_USER: exampleuser1
      WORDPRESS_DB_PASSWORD: examplepass1
      WORDPRESS_DB_NAME: exampledb1
    volumes:
      - wordpress1:/var/www/html

  db1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb1
      MYSQL_USER: exampleuser1
      MYSQL_PASSWORD: examplepass1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db1:/var/lib/mysql

  adguard-home:
        container_name: adguard-home
        image: adguard/adguardhome
        restart: always

        cap_add:
            - NET_ADMIN

        volumes:
            - '/volume1/docker/adguard-home/work:/opt/adguardhome/work'
            - '/volume1/docker/adguard-home/conf:/opt/adguardhome/conf'

        ports:
            - 53/tcp
            - 192.168.50.52:53:53/udp
            - 67/udp
            - 68/tcp
            - 68/udp
            - 82:80/tcp
            - 443/tcp
            - 853/tcp
            - 3000:3000

        hostname: adguard-home-dns
        dns:
            - 127.0.0.1
            - 1.1.1.1
volumes:
  wordpress1:
  db1:
